### ISSUE TITLE
Create notifications for various events

### ISSUE THREAD

**Issue by RohitKumarGit** [onehashai/bettersaas#15]
Create notifications for various events through whatsapp ,email , message , SMS

Events are :
1. New site creation welcome
2. 5 days before site expiry ( of trial )
3. 1 day before site expiry ( of trial )
4. 7 days before site deletion

@gadiarohit add more events or suggest changes

**Comment by Abhishek-Chougule** [comment]
whatsapp sigup notification, expiry email done.
